# Generated by Django 4.2.16 on 2024-10-09 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_auctionlisting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='price',
            new_name='current_bid',
        ),
    ]
