# Generated by Django 4.2.16 on 2024-10-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlisting',
            old_name='datetime_submited',
            new_name='datetime_submitted',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='datetime_submited',
            new_name='datetime_submitted',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='datetime_submited',
            new_name='datetime_submitted',
        ),
    ]
